/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.CtrlUsuario;
import Modelo.ClsConsultaUsuarios;
import Modelo.ClsUsuario;

/**
 *
 * @author ecede
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        fondo = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        lbluser = new javax.swing.JLabel();
        Contenedor = new javax.swing.JPanel();
        lblimagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menuventasautos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuclientes = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuventas = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuusuarios = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbltitulo.setText("GESTION VENTAS DE AUTOS");

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(lbltitulo)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        lbluser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbluser.setText("Usuario");
        getContentPane().add(lbluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 410, -1));

        lblimagen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblimagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG1.1/WhatsApp Image 2025-04-12 at 00.19.29.jpeg"))); // NOI18N
        lblimagen.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 820, 510));

        jMenuBar1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG1.1/WhatsApp Image 2025-04-12 at 12.21.46.jpeg"))); // NOI18N
        jMenu3.setText("Gestion");

        menuventasautos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuventasautos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG1.1/WhatsApp Image 2025-04-11 at 23.27.05.jpeg"))); // NOI18N
        menuventasautos.setText("Autos");
        jMenu3.add(menuventasautos);
        jMenu3.add(jSeparator1);

        menuclientes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG1.1/Usuario.jpeg"))); // NOI18N
        menuclientes.setText("Clientes");
        menuclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuclientesActionPerformed(evt);
            }
        });
        jMenu3.add(menuclientes);
        jMenu3.add(jSeparator2);

        menuventas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG1.1/WhatsApp Image 2025-04-11 at 23.40.23.jpeg"))); // NOI18N
        menuventas.setText("Ventas");
        jMenu3.add(menuventas);

        jMenuBar1.add(jMenu3);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG1.1/WhatsApp Image 2025-04-12 at 12.21.46 (1).jpeg"))); // NOI18N
        jMenu1.setText("Usuarios");

        menuusuarios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuusuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG1.1/us2.jpeg"))); // NOI18N
        menuusuarios.setText("Registros de usuarios");
        menuusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuusuariosActionPerformed(evt);
            }
        });
        jMenu1.add(menuusuarios);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuclientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuclientesActionPerformed

    private void menuusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuusuariosActionPerformed
        ClsUsuario usuario = new ClsUsuario();
        ClsConsultaUsuarios consultaUsuarios = new ClsConsultaUsuarios();
        frmUsuario frmUsuario1 = new frmUsuario();
        CtrlUsuario ctrl = new CtrlUsuario(usuario,consultaUsuarios,frmUsuario1);
        ctrl.Iniciar();
        this.lblimagen.setVisible(false);
        this.lbltitulo.setVisible(false);
        this.fondo.setVisible(false);
        Contenedor.add(frmUsuario1);
        frmUsuario1.setLocation((Contenedor.getWidth()-frmUsuario1.getWidth())/2, (Contenedor.getHeight()-frmUsuario1.getHeight())/2);
        frmUsuario1.setVisible(true);
    }//GEN-LAST:event_menuusuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    public javax.swing.JPanel fondo;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu3;
    public javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    public javax.swing.JLabel lblimagen;
    public javax.swing.JLabel lbltitulo;
    public javax.swing.JLabel lbluser;
    public javax.swing.JMenuItem menuclientes;
    public javax.swing.JMenuItem menuusuarios;
    public javax.swing.JMenuItem menuventas;
    public javax.swing.JMenuItem menuventasautos;
    // End of variables declaration//GEN-END:variables
}
