/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.CtrlClientes;
import Controlador.CtrlUsuario;
import Modelo.ClsClientes;
import Modelo.ClsConsultaClientes;
import Modelo.ClsConsultaUsuarios;
import Modelo.ClsUsuario;

/**
 *
 * @author ecede
 */
public class frmPrincipal extends javax.swing.JFrame {

    public boolean vis;

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();

        if (vis == false) {

            this.panelfondo.setVisible(true);
            this.Contenedor.setVisible(false);
        } else {
            this.panelfondo.setVisible(false);
            this.Contenedor.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        Contenedor = new javax.swing.JPanel();
        Panelusuariolog = new javax.swing.JPanel();
        lbluser = new javax.swing.JLabel();
        panelfondo = new javax.swing.JPanel();
        fondo = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        lblimagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menuventasautos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuclientes = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuventas = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuusuarios = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        getContentPane().add(Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 820, 590));

        Panelusuariolog.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbluser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbluser.setText("Usuario");

        javax.swing.GroupLayout PanelusuariologLayout = new javax.swing.GroupLayout(Panelusuariolog);
        Panelusuariolog.setLayout(PanelusuariologLayout);
        PanelusuariologLayout.setHorizontalGroup(
            PanelusuariologLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelusuariologLayout.createSequentialGroup()
                .addContainerGap(342, Short.MAX_VALUE)
                .addComponent(lbluser, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        PanelusuariologLayout.setVerticalGroup(
            PanelusuariologLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelusuariologLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbluser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(Panelusuariolog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 40));

        panelfondo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbltitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbltitulo.setText("GESTION VENTAS DE AUTOS");

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
            .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbltitulo)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
            .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(lbltitulo)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        lblimagen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblimagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG1.1/WhatsApp Image 2025-04-12 at 00.19.29.jpeg"))); // NOI18N
        lblimagen.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        javax.swing.GroupLayout panelfondoLayout = new javax.swing.GroupLayout(panelfondo);
        panelfondo.setLayout(panelfondoLayout);
        panelfondoLayout.setHorizontalGroup(
            panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
            .addGroup(panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelfondoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelfondoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );
        panelfondoLayout.setVerticalGroup(
            panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
            .addGroup(panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelfondoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelfondoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(9, Short.MAX_VALUE)))
        );

        getContentPane().add(panelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 710, 430));

        jMenuBar1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG1.1/WhatsApp Image 2025-04-12 at 12.21.46.jpeg"))); // NOI18N
        jMenu3.setText("Gestion");

        menuventasautos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuventasautos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG1.1/WhatsApp Image 2025-04-11 at 23.27.05.jpeg"))); // NOI18N
        menuventasautos.setText("Autos");
        jMenu3.add(menuventasautos);
        jMenu3.add(jSeparator1);

        menuclientes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG1.1/Usuario.jpeg"))); // NOI18N
        menuclientes.setText("Clientes");
        menuclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuclientesActionPerformed(evt);
            }
        });
        jMenu3.add(menuclientes);
        jMenu3.add(jSeparator2);

        menuventas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG1.1/WhatsApp Image 2025-04-11 at 23.40.23.jpeg"))); // NOI18N
        menuventas.setText("Ventas");
        jMenu3.add(menuventas);

        jMenuBar1.add(jMenu3);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG1.1/WhatsApp Image 2025-04-12 at 12.21.46 (1).jpeg"))); // NOI18N
        jMenu1.setText("Usuarios");

        menuusuarios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuusuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG1.1/us2.jpeg"))); // NOI18N
        menuusuarios.setText("Registros de usuarios");
        menuusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuusuariosActionPerformed(evt);
            }
        });
        jMenu1.add(menuusuarios);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuclientesActionPerformed
        ClsClientes clientes = new ClsClientes();
        ClsConsultaClientes consultaClientes = new ClsConsultaClientes();
        frmCliente frmCliente1 = new frmCliente();
        CtrlClientes ctrlClientes = new CtrlClientes(clientes, consultaClientes, frmCliente1, this);
        ctrlClientes.Iniciar();
        vis = true;

        if (vis == true) {
            this.panelfondo.setVisible(false);
            this.Contenedor.setVisible(true);

            Contenedor.add(frmCliente1);
            frmCliente1.setLocation((Contenedor.getWidth() - frmCliente1.getWidth()) / 2, (Contenedor.getHeight() - frmCliente1.getHeight()) / 2);
            frmCliente1.setVisible(true);
        }

    }//GEN-LAST:event_menuclientesActionPerformed

    /* public void ACtivar() {
        if (ctrlClientes.visible == true) {
            vis = true;
        } else {
            vis = false;
        }
    }*/
    private void menuusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuusuariosActionPerformed
        ClsUsuario usuario = new ClsUsuario();
        ClsConsultaUsuarios consultaUsuarios = new ClsConsultaUsuarios();
        frmUsuario frmUsuario1 = new frmUsuario();
        CtrlUsuario ctrl = new CtrlUsuario(usuario, consultaUsuarios, frmUsuario1, this);
        ctrl.Iniciar();
        vis = true;
        if (vis == true) {
            this.panelfondo.setVisible(false);
            this.Contenedor.setVisible(true);
            Contenedor.add(frmUsuario1);
            frmUsuario1.setLocation((Contenedor.getWidth() - frmUsuario1.getWidth()) / 2, (Contenedor.getHeight() - frmUsuario1.getHeight()) / 2);
            frmUsuario1.setVisible(true);
        }


    }//GEN-LAST:event_menuusuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Contenedor;
    private javax.swing.JPanel Panelusuariolog;
    public javax.swing.JPanel fondo;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu3;
    public javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    public javax.swing.JLabel lblimagen;
    public javax.swing.JLabel lbltitulo;
    public javax.swing.JLabel lbluser;
    public javax.swing.JMenuItem menuclientes;
    public javax.swing.JMenuItem menuusuarios;
    public javax.swing.JMenuItem menuventas;
    public javax.swing.JMenuItem menuventasautos;
    public javax.swing.JPanel panelfondo;
    // End of variables declaration//GEN-END:variables
}
