/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.ClsAutos;
import Modelo.ClsClientes;

/**
 *
 * @author monta
 */
public class frmVentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmVentas
     */
    public frmVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        favicon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JVentas = new javax.swing.JTable();
        btnactualizar = new javax.swing.JButton();
        btncerrarformulario = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cmbclientes = new javax.swing.JComboBox<>();
        cmbautos = new javax.swing.JComboBox<>();
        fecha = new com.toedter.calendar.JDateChooser();
        txtprecio = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(842, 536));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        favicon.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        favicon.setText("CONCESIONARIA DE AUTOS");
        getContentPane().add(favicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        jLabel2.setText("Registra nueva venta");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 116, 197));
        jSeparator2.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 830, 10));

        jSeparator1.setForeground(new java.awt.Color(0, 116, 197));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(60, 60));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 20, 450));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Buscar:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        txtbuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 290, 40));

        jLabel1.setText("Ventas Registradas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        JVentas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Auto", "Cliente", "Fecha", "Precio"
            }
        ));
        jScrollPane1.setViewportView(JVentas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 390, 240));

        btnactualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG1.1/refresh_5794960.png"))); // NOI18N
        btnactualizar.setText("Actualizar tabla");
        btnactualizar.setBorder(null);
        getContentPane().add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 150, 40));

        btncerrarformulario.setBackground(new java.awt.Color(0, 116, 197));
        btncerrarformulario.setForeground(new java.awt.Color(255, 255, 255));
        btncerrarformulario.setText("Cerrar Formulario");
        btncerrarformulario.setBorder(null);
        getContentPane().add(btncerrarformulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 120, 40));

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG1.1/eliminar.png"))); // NOI18N
        btneliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG1.1/editar.png"))); // NOI18N
        btneditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        btnguardar.setForeground(new java.awt.Color(153, 153, 255));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG1.1/guardar.png"))); // NOI18N
        btnguardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        txtid.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 30));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("Fecha de venta:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("Clientes:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("Auto:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setText("Precio final:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        cmbclientes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbclientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(cmbclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 340, 40));

        cmbautos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbautos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(cmbautos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 170, 40));

        fecha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 200, 40));

        txtprecio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtprecio.setEnabled(false);
        getContentPane().add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable JVentas;
    public javax.swing.JButton btnactualizar;
    public javax.swing.JButton btncerrarformulario;
    public javax.swing.JButton btneditar;
    public javax.swing.JButton btneliminar;
    public javax.swing.JButton btnguardar;
    public javax.swing.JComboBox<ClsAutos> cmbautos;
    public javax.swing.JComboBox<ClsClientes> cmbclientes;
    private javax.swing.JLabel favicon;
    public com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextField txtbuscar;
    public javax.swing.JTextField txtid;
    public javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
